# Generated by Django 4.2.6 on 2023-11-02 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vinos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=30)),
                ('bodega', models.CharField(max_length=30)),
                ('uva', models.CharField(max_length=30)),
                ('cosecha', models.IntegerField()),
                ('precio', models.FloatField()),
            ],
        ),
    ]
