# Generated by Django 4.2.6 on 2023-11-11 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='maridajes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cepa', models.CharField(max_length=30)),
                ('maridaje', models.CharField(max_length=30)),
                ('marcasrecomendadas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='regiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('provincias', models.CharField(max_length=30)),
                ('clima', models.CharField(max_length=30)),
                ('suelo', models.IntegerField()),
                ('cepas', models.IntegerField()),
                ('bodegas', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='tips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etiqueta', models.TextField()),
                ('maridaje', models.CharField(max_length=30)),
                ('reseñas', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='vinos',
            name='precio',
            field=models.IntegerField(),
        ),
    ]
