# Generated by Django 4.2.6 on 2023-11-11 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_maridajes_regiones_tips_alter_vinos_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vinos',
            old_name='uva',
            new_name='cepa',
        ),
    ]
